### ISSUE TITLE
RemoteData vs WebData

### ISSUE THREAD

**Issue by janwirth** [Gizra/elm-editable-webdata#6]
This package is using `krisajenkins/remotedata` rather than WebData. Does it make sense to adjust the naming in order to be consistend in projects using both packages?

**Comment by amitaibu** [comment]
We are actually using just `WebData` - https://github.com/Gizra/elm-editable-webdata/blob/0b3e3319f8d17a94a5532c5c5232668e8e986efa/src/Editable/WebData.elm#L48

I guess we could have used RemoteData as-well, if there was a real world use case for it :)

**Comment by janwirth** [comment]
Oh I'm sorry - I was reading through the `elm.json`.
https://github.com/Gizra/elm-editable-webdata/blob/master/elm.json#L14
